baseURL = 'https://forsaken-cabal.github.io/Wiki/'
languageCode = 'en-us'
title = 'Forsaken Wiki'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.docs]
darkMode = true
themeColor = 'red'
title = 'Forsaken Wiki'

[params.footer]
copyright = 'Forsaken Wiki'